############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Comandos Essenciais"
url = "/comandos-essenciais-simulacao"
weight = 2

[[main]]
name = "Diário de Bordo"
url = "/diario-de-bordo"
weight = 3

[[main]]
parent = "Pages"
name = "404 Page"
url = "/404"
